/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manejo.*;

/**
 *
 * @author Ing. Hector Acevedo
 */
public class ReporteGeneral extends javax.swing.JFrame {

    ManejoInformacion manejo = ManejoInformacion.getManejo();
    private DepartamentoCuidado departamento;

    DefaultTableModel modeloMonteria = new DefaultTableModel();
    DefaultTableModel modeloSahagun = new DefaultTableModel();
    DefaultTableModel modeloLorica = new DefaultTableModel();

    /**
     * Creates new form ReporteGeneral
     */
    public ReporteGeneral() {
        initComponents();

        String titulos[] = new String[]{"NOMBRE DEL NIÑ@", "IDENTIFICACION(NIÑ@)", "PESO", "ESTATURA", "EDAD", "REPRESENTANTE", "IDENTIFICACION", "PARENTESCO"};
        //Modelo de la tabla pra monteria
        modeloMonteria.setColumnIdentifiers(titulos);
        jtbl_reporteMonterial.setModel(modeloMonteria);
        //Modelo de la tabla para sahagun
        modeloSahagun.setColumnIdentifiers(titulos);
        jtbl_reporteSahagun.setModel(modeloSahagun);
        //Modelo de la tabla pra lorica
        modeloLorica.setColumnIdentifiers(titulos);
        jtbl_reporteLorica.setModel(modeloLorica);

        cargarNinos(); //Metodo para cargar los niños bajos en estatura y peso

        //Se cargan los datos en las tablas de los departamentos
        cargarInfoMonteria();
        cargarInfoSahagun();
        cargarInfoLorica();
    }

    public void setDepartamentoCuidado(DepartamentoCuidado departamento) {
        this.departamento = departamento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtp_reporteMunicipios = new javax.swing.JTabbedPane();
        jpl_monteria = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_reporteMonterial = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_bajoPesoMonteria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_bajoTallaMonteria = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_idNinoMonteria = new javax.swing.JTextField();
        cbo_opcionesMonteria = new javax.swing.JComboBox<>();
        btn_aceptarMonteria = new javax.swing.JButton();
        jpl_sahagun = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_reporteSahagun = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_bajoPesoSahagun = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_bajoTallaSahagun = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_idNinoSahagun = new javax.swing.JTextField();
        cbo_opcionesSahagun = new javax.swing.JComboBox<>();
        btn_aceptarSahagun = new javax.swing.JButton();
        jpl_lorica = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbl_reporteLorica = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_bajoPesoLorica = new javax.swing.JTextField();
        txt_bajoTallaLorica = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_idNinoLorica = new javax.swing.JTextField();
        cbo_opcionesLorica = new javax.swing.JComboBox<>();
        btn_aceptarLorica = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE GENERAL DE NIÑOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Reporte general del Departamento del cuidado de niños bajos en peso.");

        jtp_reporteMunicipios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Reporte del municipio de Monteria:");

        jtbl_reporteMonterial.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jtbl_reporteMonterial);

        jLabel6.setText("Niños bajos en peso:");

        jLabel7.setText("Niños bajos de estatura:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setText("Buscar o eliminar registro de niñ@:");

        jLabel17.setText("Identificacion (niñ@):");

        cbo_opcionesMonteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Buscar", "Eliminar"}));

        btn_aceptarMonteria.setText("ACEPTAR");
        btn_aceptarMonteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarMonteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_monteriaLayout = new javax.swing.GroupLayout(jpl_monteria);
        jpl_monteria.setLayout(jpl_monteriaLayout);
        jpl_monteriaLayout.setHorizontalGroup(
                jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane1)
                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txt_bajoPesoMonteria))
                                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txt_bajoTallaMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                                .addGap(6, 6, 6)
                                                                                .addComponent(jLabel17)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(txt_idNinoMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(cbo_opcionesMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(33, 33, 33)
                                                                                .addComponent(btn_aceptarMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 54, Short.MAX_VALUE)))))
                                .addContainerGap())
        );
        jpl_monteriaLayout.setVerticalGroup(
                jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(txt_bajoPesoMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(txt_bajoTallaMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jpl_monteriaLayout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jpl_monteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel17)
                                                                        .addComponent(txt_idNinoMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbo_opcionesMonteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn_aceptarMonteria))))
                                                .addGap(0, 11, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jtp_reporteMunicipios.addTab("MONTERIA", jpl_monteria);

        jLabel4.setText("Reporte del municipio de Sahagun:");

        jtbl_reporteSahagun.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(jtbl_reporteSahagun);

        jLabel8.setText("Niños bajos en peso:");

        jLabel9.setText("Niños bajos de estatura:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setText("Buscar o eliminar registro de niñ@:");

        jLabel15.setText("Identificacion (niñ@):");

        cbo_opcionesSahagun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Buscar", "Eliminar"}));

        btn_aceptarSahagun.setText("ACEPTAR");
        btn_aceptarSahagun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarSahagunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_sahagunLayout = new javax.swing.GroupLayout(jpl_sahagun);
        jpl_sahagun.setLayout(jpl_sahagunLayout);
        jpl_sahagunLayout.setHorizontalGroup(
                jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_bajoPesoSahagun))
                                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_bajoTallaSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(40, 40, 40)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_idNinoSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbo_opcionesSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(btn_aceptarSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 54, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap())
        );
        jpl_sahagunLayout.setVerticalGroup(
                jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3)
                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel8)
                                                                        .addComponent(txt_bajoPesoSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(txt_bajoTallaSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jpl_sahagunLayout.createSequentialGroup()
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jpl_sahagunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel15)
                                                                        .addComponent(txt_idNinoSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbo_opcionesSahagun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn_aceptarSahagun))))
                                                .addGap(0, 11, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jtp_reporteMunicipios.addTab("SAHAGUN", jpl_sahagun);

        jLabel5.setText("Reporte del municipio de Lorica:");

        jtbl_reporteLorica.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane3.setViewportView(jtbl_reporteLorica);

        jLabel10.setText("Niños bajos en peso:");

        jLabel11.setText("Niños bajos de estatura:");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setText("Buscar o eliminar registro de niñ@:");

        jLabel13.setText("Identificacion (niñ@):");

        cbo_opcionesLorica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Buscar", "Eliminar"}));

        btn_aceptarLorica.setText("ACEPTAR");
        btn_aceptarLorica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarLoricaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpl_loricaLayout = new javax.swing.GroupLayout(jpl_lorica);
        jpl_lorica.setLayout(jpl_loricaLayout);
        jpl_loricaLayout.setHorizontalGroup(
                jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_bajoPesoLorica))
                                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_bajoTallaLorica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(40, 40, 40)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_idNinoLorica, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cbo_opcionesLorica, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(btn_aceptarLorica, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 54, Short.MAX_VALUE))
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
        );
        jpl_loricaLayout.setVerticalGroup(
                jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator4)
                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel10)
                                                                        .addComponent(txt_bajoPesoLorica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(txt_bajoTallaLorica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jpl_loricaLayout.createSequentialGroup()
                                                                .addComponent(jLabel12)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jpl_loricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(txt_idNinoLorica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cbo_opcionesLorica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btn_aceptarLorica))))
                                                .addGap(0, 11, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jtp_reporteMunicipios.addTab("LORICA", jpl_lorica);

        btn_regresar.setText("REGRESAR");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtp_reporteMunicipios)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtp_reporteMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_regresar)
                                        .addComponent(btn_salir))
                                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para cargar los niños bajos en peso y estatura por cada municipio
    private void cargarNinos(){
        //Cargar la cantidad de niños que hay con bajo peso en cada municipio
        txt_bajoPesoMonteria.setText(String.valueOf(manejo.bajoPesoMonteria()));
        txt_bajoPesoSahagun.setText(String.valueOf(manejo.bajopesoSahagun()));
        txt_bajoPesoLorica.setText(String.valueOf(manejo.bajoPesoLorica()));

        //Cargar la cantidad de niños que hay con baja estatura en cada municipio
        txt_bajoTallaMonteria.setText(String.valueOf(manejo.estaturaBajaMonteria()));
        txt_bajoTallaSahagun.setText(String.valueOf(manejo.estaturaBajaSagahun()));
        txt_bajoTallaLorica.setText(String.valueOf(manejo.EstaturaBajaLorica()));
    }
    
    //Mostrar datos en las tablas
    private void cargarInfoMonteria() {
        Informacion temp = manejo.getCabeza();
        while (temp != null) {
            if (temp.getMunicipio().equals("Monteria")) {
                String nombreNino = temp.getNombreNino();
                int idNino = temp.getIdentificacionNino();
                int peso = temp.getPeso();
                float estatura = temp.getEstatura();
                int edad = temp.getEdad();
                String representante = temp.getNomRepresentante();
                int idRepresentante = temp.getIdRepresentante();
                String parentesco = temp.getParentesco();

                Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                modeloMonteria.addRow(listar);
                temp = temp.getSiguiente();
            }
        }
    }

    private void cargarInfoSahagun() {
        Informacion temp = manejo.getCabeza();
        while (temp != null) {
            if (temp.getMunicipio().equals("Sahagun")) {
                String nombreNino = temp.getNombreNino();
                int idNino = temp.getIdentificacionNino();
                int peso = temp.getPeso();
                float estatura = temp.getEstatura();
                int edad = temp.getEdad();
                String representante = temp.getNomRepresentante();
                int idRepresentante = temp.getIdRepresentante();
                String parentesco = temp.getParentesco();

                Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                modeloSahagun.addRow(listar);
                temp = temp.getSiguiente();
            }
        }
    }

    private void cargarInfoLorica() {
        Informacion temp = manejo.getCabeza();
        while (temp != null) {
            if (temp.getMunicipio().equals("Lorica")) {
                String nombreNino = temp.getNombreNino();
                int idNino = temp.getIdentificacionNino();
                int peso = temp.getPeso();
                float estatura = temp.getEstatura();
                int edad = temp.getEdad();
                String representante = temp.getNomRepresentante();
                int idRepresentante = temp.getIdRepresentante();
                String parentesco = temp.getParentesco();

                Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                modeloLorica.addRow(listar);
                temp = temp.getSiguiente();
            }
        }
    }

    private void btn_aceptarMonteriaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_aceptarMonteriaActionPerformed
        try {
            int identificacion = Integer.parseInt(txt_idNinoMonteria.getText());
            int opcion = cbo_opcionesMonteria.getSelectedIndex();

            Informacion informacion = manejo.buscar(identificacion);

            switch (opcion) {
                case 0: // buscar
                    if (informacion != null && informacion.getMunicipio().equals("Monteria")) {
                        modeloMonteria.setRowCount(0); // Limpiar la tabla antes de mostrar la informacion encontrada

                        String nombreNino = informacion.getNombreNino();
                        int idNino = informacion.getIdentificacionNino();
                        int peso = informacion.getPeso();
                        float estatura = informacion.getEstatura();
                        int edad = informacion.getEdad();
                        String representante = informacion.getNomRepresentante();
                        int idRepresentante = informacion.getIdRepresentante();
                        String parentesco = informacion.getParentesco();

                        Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                        modeloMonteria.addRow(listar);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                        txt_idNinoMonteria.grabFocus();
                    }
                    break;
                case 1: //Eliminar
                    if (informacion != null) {
                        manejo.eliminar(informacion);
                        JOptionPane.showMessageDialog(null, "Se ha eliminado la informacion del niño correctamente", null, JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                        txt_idNinoMonteria.grabFocus();
                    }
                    break;
            }
        } catch (Exception e) {

        }
    }// GEN-LAST:event_btn_aceptarMonteriaActionPerformed

    private void btn_aceptarSahagunActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_aceptarSahagunActionPerformed
        try {
                int identificacion = Integer.parseInt(txt_idNinoSahagun.getText());
                int opcion = cbo_opcionesSahagun.getSelectedIndex();
    
                Informacion informacion = manejo.buscar(identificacion);
    
                switch (opcion) {
                    case 0: // buscar
                        if (informacion != null && informacion.getMunicipio().equals("Sahagún")) {
                            modeloSahagun.setRowCount(0); // Limpiar la tabla antes de mostrar la informacion encontrada
    
                            String nombreNino = informacion.getNombreNino();
                            int idNino = informacion.getIdentificacionNino();
                            int peso = informacion.getPeso();
                            float estatura = informacion.getEstatura();
                            int edad = informacion.getEdad();
                            String representante = informacion.getNomRepresentante();
                            int idRepresentante = informacion.getIdRepresentante();
                            String parentesco = informacion.getParentesco();
    
                            Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                            modeloSahagun.addRow(listar);
                        } else {
                            JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                            txt_idNinoSahagun.grabFocus();
                        }
                        break;
                    case 1: //Eliminar
                        if (informacion != null) {
                            manejo.eliminar(informacion);
                            JOptionPane.showMessageDialog(null, "Se ha eliminado la informacion del niño correctamente", null, JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                            txt_idNinoSahagun.grabFocus();
                        }
                        break;
                }
            } catch (Exception e) {
    
            }
    }// GEN-LAST:event_btn_aceptarSahagunActionPerformed

    private void btn_aceptarLoricaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_aceptarLoricaActionPerformed
        try {
                int identificacion = Integer.parseInt(txt_idNinoLorica.getText());
                int opcion = cbo_opcionesLorica.getSelectedIndex();
    
                Informacion informacion = manejo.buscar(identificacion);
    
                switch (opcion) {
                    case 0: // buscar
                        if (informacion != null && informacion.getMunicipio().equals("Lorica")) {
                            modeloLorica.setRowCount(0); // Limpiar la tabla antes de mostrar la informacion encontrada
    
                            String nombreNino = informacion.getNombreNino();
                            int idNino = informacion.getIdentificacionNino();
                            int peso = informacion.getPeso();
                            float estatura = informacion.getEstatura();
                            int edad = informacion.getEdad();
                            String representante = informacion.getNomRepresentante();
                            int idRepresentante = informacion.getIdRepresentante();
                            String parentesco = informacion.getParentesco();
    
                            Object listar[] = new Object[]{nombreNino, idNino, peso, estatura, edad, representante, idRepresentante, parentesco};
                            modeloLorica.addRow(listar);
                        } else {
                            JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                            txt_idNinoLorica.grabFocus();
                        }
                        break;
                    case 1: //Eliminar
                        if (informacion != null) {
                            manejo.eliminar(informacion);
                            JOptionPane.showMessageDialog(null, "Se ha eliminado la informacion del niño correctamente", null, JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "No se ha encontrado la informacion, por favor verifique la identificacion", null, JOptionPane.ERROR_MESSAGE);
                            txt_idNinoLorica.grabFocus();
                        }
                        break;
                }
            } catch (Exception e) {
    
            }
    }// GEN-LAST:event_btn_aceptarLoricaActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_regresarActionPerformed
        departamento.setVisible(true);
        departamento.setLocationRelativeTo(null);
        departamento.setResizable(false);
        this.setVisible(false);
    }// GEN-LAST:event_btn_regresarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }// GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarLorica;
    private javax.swing.JButton btn_aceptarMonteria;
    private javax.swing.JButton btn_aceptarSahagun;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbo_opcionesLorica;
    private javax.swing.JComboBox<String> cbo_opcionesMonteria;
    private javax.swing.JComboBox<String> cbo_opcionesSahagun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel jpl_lorica;
    private javax.swing.JPanel jpl_monteria;
    private javax.swing.JPanel jpl_sahagun;
    private javax.swing.JTable jtbl_reporteLorica;
    private javax.swing.JTable jtbl_reporteMonterial;
    private javax.swing.JTable jtbl_reporteSahagun;
    private javax.swing.JTabbedPane jtp_reporteMunicipios;
    private javax.swing.JTextField txt_bajoPesoLorica;
    private javax.swing.JTextField txt_bajoPesoMonteria;
    private javax.swing.JTextField txt_bajoPesoSahagun;
    private javax.swing.JTextField txt_bajoTallaLorica;
    private javax.swing.JTextField txt_bajoTallaMonteria;
    private javax.swing.JTextField txt_bajoTallaSahagun;
    private javax.swing.JTextField txt_idNinoLorica;
    private javax.swing.JTextField txt_idNinoMonteria;
    private javax.swing.JTextField txt_idNinoSahagun;
    // End of variables declaration//GEN-END:variables
}
